### ISSUE TITLE
Usage with io.js ?

### ISSUE THREAD

**Issue by ColCh** [c4milo/node-webkit-agent#77]
Try to use on io.js with version:
```shell
myguestuser@91614db4b948:/srv$ node --version
v1.1.0
```
Installation log:
```shell
myguestuser@91614db4b948:/srv$ npm install webkit-devtools-agent
-
> ws@0.4.31 install /srv/node_modules/webkit-devtools-agent/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/srv/node_modules/webkit-devtools-agent/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:88: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/srv/node_modules/webkit-devtools-agent/node_modules/ws/build'

> webkit-devtools-agent@0.3.1 install /srv/node_modules/webkit-devtools-agent
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/srv/node_modules/webkit-devtools-agent/build'
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
In file included from ../src/cpu_profiler.cc:1:0:
../src/cpu_profiler.h:19:57: error: 'Arguments' does not name a type
             static Handle<Value> GetProfilesCount(const Arguments& args);
                                                         ^
../src/cpu_profiler.h:20:51: error: 'Arguments' does not name a type
             static Handle<Value> GetProfile(const Arguments& args);
                                                   ^
../src/cpu_profiler.h:21:52: error: 'Arguments' does not name a type
             static Handle<Value> FindProfile(const Arguments& args);
                                                    ^
../src/cpu_profiler.h:22:55: error: 'Arguments' does not name a type
             static Handle<Value> StartProfiling(const Arguments& args);
                                                       ^
../src/cpu_profiler.h:23:54: error: 'Arguments' does not name a type
             static Handle<Value> StopProfiling(const Arguments& args);
                                                      ^
../src/cpu_profiler.h:24:58: error: 'Arguments' does not name a type
             static Handle<Value> DeleteAllProfiles(const Arguments& args);
                                                          ^
In file included from ../src/cpu_profiler.cc:2:0:
../src/profile.h:16:61: error: 'AccessorInfo' does not name a type
   static Handle<Value> GetUid(Local<String> property, const AccessorInfo& info);
                                                             ^
../src/profile.h:17:63: error: 'AccessorInfo' does not name a type
   static Handle<Value> GetTitle(Local<String> property, const AccessorInfo& info);
                                                               ^
../src/profile.h:18:65: error: 'AccessorInfo' does not name a type
   static Handle<Value> GetTopRoot(Local<String> property, const AccessorInfo& info);
                                                                 ^
../src/profile.h:19:68: error: 'AccessorInfo' does not name a type
   static Handle<Value> GetBottomRoot(Local<String> property, const AccessorInfo& info);
                                                                    ^
../src/profile.h:20:37: error: 'Arguments' does not name a type
   static Handle<Value> Delete(const Arguments& args);
                                     ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h: In static member function 'static void nodex::CpuProfiler::Initialize(v8::Handle<v8::Object>)':
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: error: 'v8::HandleScope::HandleScope()' is protected
   V8_INLINE HandleScope() {}
             ^
../src/cpu_profiler.cc:8:21: error: within this context
         HandleScope scope;
                     ^
../src/cpu_profiler.cc:10:87: error: no matching function for call to 'v8::Persistent<v8::ObjectTemplate>::New(v8::Local<v8::ObjectTemplate>)'
         cpu_profiler_template_ = Persistent<ObjectTemplate>::New(ObjectTemplate::New());
                                                                                       ^
../src/cpu_profiler.cc:10:87: note: candidate is:
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:6462:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::ObjectTemplate]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:6462:4: note:   candidate expects 2 arguments, 1 provided
../src/cpu_profiler.cc:11:31: error: base operand of '->' has non-pointer type 'v8::Persistent<v8::ObjectTemplate>'
         cpu_profiler_template_->SetInternalFieldCount(1);
                               ^
../src/cpu_profiler.cc:13:62: error: base operand of '->' has non-pointer type 'v8::Persistent<v8::ObjectTemplate>'
         Local<Object> cpuProfilerObj = cpu_profiler_template_->NewInstance();
                                                              ^
../src/cpu_profiler.cc:15:90: error: no matching function for call to 'NODE_SET_METHOD(v8::Local<v8::Object>&, const char [17], v8::Handle<v8::Value> (&)(const int&))'
         NODE_SET_METHOD(cpuProfilerObj, "getProfilesCount", CpuProfiler::GetProfilesCount);
                                                                                          ^
../src/cpu_profiler.cc:15:90: note: candidate is:
In file included from ../src/cpu_profiler.h:4:0,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note:   template argument deduction/substitution failed:
../src/cpu_profiler.cc:15:90: note:   cannot convert 'nodex::CpuProfiler::GetProfilesCount' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
         NODE_SET_METHOD(cpuProfilerObj, "getProfilesCount", CpuProfiler::GetProfilesCount);
                                                                                          ^
../src/cpu_profiler.cc:16:78: error: no matching function for call to 'NODE_SET_METHOD(v8::Local<v8::Object>&, const char [11], v8::Handle<v8::Value> (&)(const int&))'
         NODE_SET_METHOD(cpuProfilerObj, "getProfile", CpuProfiler::GetProfile);
                                                                              ^
../src/cpu_profiler.cc:16:78: note: candidate is:
In file included from ../src/cpu_profiler.h:4:0,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note:   template argument deduction/substitution failed:
../src/cpu_profiler.cc:16:78: note:   cannot convert 'nodex::CpuProfiler::GetProfile' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
         NODE_SET_METHOD(cpuProfilerObj, "getProfile", CpuProfiler::GetProfile);
                                                                              ^
../src/cpu_profiler.cc:17:80: error: no matching function for call to 'NODE_SET_METHOD(v8::Local<v8::Object>&, const char [12], v8::Handle<v8::Value> (&)(const int&))'
         NODE_SET_METHOD(cpuProfilerObj, "findProfile", CpuProfiler::FindProfile);
                                                                                ^
../src/cpu_profiler.cc:17:80: note: candidate is:
In file included from ../src/cpu_profiler.h:4:0,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note:   template argument deduction/substitution failed:
../src/cpu_profiler.cc:17:80: note:   cannot convert 'nodex::CpuProfiler::FindProfile' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
         NODE_SET_METHOD(cpuProfilerObj, "findProfile", CpuProfiler::FindProfile);
                                                                                ^
../src/cpu_profiler.cc:18:86: error: no matching function for call to 'NODE_SET_METHOD(v8::Local<v8::Object>&, const char [15], v8::Handle<v8::Value> (&)(const int&))'
         NODE_SET_METHOD(cpuProfilerObj, "startProfiling", CpuProfiler::StartProfiling);
                                                                                      ^
../src/cpu_profiler.cc:18:86: note: candidate is:
In file included from ../src/cpu_profiler.h:4:0,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note:   template argument deduction/substitution failed:
../src/cpu_profiler.cc:18:86: note:   cannot convert 'nodex::CpuProfiler::StartProfiling' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
         NODE_SET_METHOD(cpuProfilerObj, "startProfiling", CpuProfiler::StartProfiling);
                                                                                      ^
../src/cpu_profiler.cc:19:84: error: no matching function for call to 'NODE_SET_METHOD(v8::Local<v8::Object>&, const char [14], v8::Handle<v8::Value> (&)(const int&))'
         NODE_SET_METHOD(cpuProfilerObj, "stopProfiling", CpuProfiler::StopProfiling);
                                                                                    ^
../src/cpu_profiler.cc:19:84: note: candidate is:
In file included from ../src/cpu_profiler.h:4:0,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note:   template argument deduction/substitution failed:
../src/cpu_profiler.cc:19:84: note:   cannot convert 'nodex::CpuProfiler::StopProfiling' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
         NODE_SET_METHOD(cpuProfilerObj, "stopProfiling", CpuProfiler::StopProfiling);
                                                                                    ^
../src/cpu_profiler.cc:20:92: error: no matching function for call to 'NODE_SET_METHOD(v8::Local<v8::Object>&, const char [18], v8::Handle<v8::Value> (&)(const int&))'
         NODE_SET_METHOD(cpuProfilerObj, "deleteAllProfiles", CpuProfiler::DeleteAllProfiles);
                                                                                            ^
../src/cpu_profiler.cc:20:92: note: candidate is:
In file included from ../src/cpu_profiler.h:4:0,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/myguestuser/.node-gyp/1.1.0/src/node.h:206:13: note:   template argument deduction/substitution failed:
../src/cpu_profiler.cc:20:92: note:   cannot convert 'nodex::CpuProfiler::DeleteAllProfiles' (type 'v8::Handle<v8::Value>(const int&)') to type 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}'
         NODE_SET_METHOD(cpuProfilerObj, "deleteAllProfiles", CpuProfiler::DeleteAllProfiles);
                                                                                            ^
../src/cpu_profiler.cc:22:21: error: 'NewSymbol' is not a member of 'v8::String'
         target->Set(String::NewSymbol("cpuProfiler"), cpuProfilerObj);
                     ^
../src/cpu_profiler.cc: At global scope:
../src/cpu_profiler.cc:28:55: error: 'Arguments' does not name a type
     Handle<Value> CpuProfiler::GetProfilesCount(const Arguments& args) {
                                                       ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::GetProfilesCount(const int&)':
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: error: 'v8::HandleScope::HandleScope()' is protected
   V8_INLINE HandleScope() {}
             ^
../src/cpu_profiler.cc:29:21: error: within this context
         HandleScope scope;
                     ^
../src/cpu_profiler.cc:30:22: error: 'class v8::HandleScope' has no member named 'Close'
         return scope.Close(Integer::New(v8::CpuProfiler::GetProfilesCount()));
                      ^
../src/cpu_profiler.cc:30:41: error: 'GetProfilesCount' is not a member of 'v8::CpuProfiler'
         return scope.Close(Integer::New(v8::CpuProfiler::GetProfilesCount()));
                                         ^
../src/cpu_profiler.cc: At global scope:
../src/cpu_profiler.cc:33:49: error: 'Arguments' does not name a type
     Handle<Value> CpuProfiler::GetProfile(const Arguments& args) {
                                                 ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::GetProfile(const int&)':
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: error: 'v8::HandleScope::HandleScope()' is protected
   V8_INLINE HandleScope() {}
             ^
../src/cpu_profiler.cc:34:21: error: within this context
         HandleScope scope;
                     ^
../src/cpu_profiler.cc:35:18: error: request for member 'Length' in 'args', which is of non-class type 'const int'
         if (args.Length() < 1) {
                  ^
../src/cpu_profiler.cc:36:52: error: 'New' is not a member of 'v8::String'
             return ThrowException(Exception::Error(String::New("No index specified")));
                                                    ^
../src/cpu_profiler.cc:36:86: error: 'ThrowException' was not declared in this scope
             return ThrowException(Exception::Error(String::New("No index specified")));
                                                                                      ^
../src/cpu_profiler.cc:37:27: error: invalid types 'const int[int]' for array subscript
         } else if (!args[0]->IsInt32()) {
                           ^
../src/cpu_profiler.cc:38:56: error: 'New' is not a member of 'v8::String'
             return ThrowException(Exception::TypeError(String::New("Argument must be an integer")));
                                                        ^
../src/cpu_profiler.cc:38:99: error: 'ThrowException' was not declared in this scope
             return ThrowException(Exception::TypeError(String::New("Argument must be an integer")));
                                                                                                   ^
../src/cpu_profiler.cc:40:31: error: invalid types 'const int[int]' for array subscript
         int32_t index = args[0]->Int32Value();
                               ^
../src/cpu_profiler.cc:41:37: error: 'GetProfile' is not a member of 'v8::CpuProfiler'
         const CpuProfile* profile = v8::CpuProfiler::GetProfile(index);
                                     ^
../src/cpu_profiler.cc:42:22: error: 'class v8::HandleScope' has no member named 'Close'
         return scope.Close(Profile::New(profile));
                      ^
../src/cpu_profiler.cc: At global scope:
../src/cpu_profiler.cc:45:50: error: 'Arguments' does not name a type
     Handle<Value> CpuProfiler::FindProfile(const Arguments& args) {
                                                  ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::FindProfile(const int&)':
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: error: 'v8::HandleScope::HandleScope()' is protected
   V8_INLINE HandleScope() {}
             ^
../src/cpu_profiler.cc:46:21: error: within this context
         HandleScope scope;
                     ^
../src/cpu_profiler.cc:47:18: error: request for member 'Length' in 'args', which is of non-class type 'const int'
         if (args.Length() < 1) {
                  ^
../src/cpu_profiler.cc:48:52: error: 'New' is not a member of 'v8::String'
             return ThrowException(Exception::Error(String::New("No index specified")));
                                                    ^
../src/cpu_profiler.cc:48:86: error: 'ThrowException' was not declared in this scope
             return ThrowException(Exception::Error(String::New("No index specified")));
                                                                                      ^
../src/cpu_profiler.cc:49:27: error: invalid types 'const int[int]' for array subscript
         } else if (!args[0]->IsInt32()) {
                           ^
../src/cpu_profiler.cc:50:56: error: 'New' is not a member of 'v8::String'
             return ThrowException(Exception::TypeError(String::New("Argument must be an integer")));
                                                        ^
../src/cpu_profiler.cc:50:99: error: 'ThrowException' was not declared in this scope
             return ThrowException(Exception::TypeError(String::New("Argument must be an integer")));
                                                                                                   ^
../src/cpu_profiler.cc:52:30: error: invalid types 'const int[int]' for array subscript
         uint32_t uid = args[0]->Uint32Value();
                              ^
../src/cpu_profiler.cc:53:37: error: 'FindProfile' is not a member of 'v8::CpuProfiler'
         const CpuProfile* profile = v8::CpuProfiler::FindProfile(uid);
                                     ^
../src/cpu_profiler.cc:54:22: error: 'class v8::HandleScope' has no member named 'Close'
         return scope.Close(Profile::New(profile));
                      ^
../src/cpu_profiler.cc: At global scope:
../src/cpu_profiler.cc:57:53: error: 'Arguments' does not name a type
     Handle<Value> CpuProfiler::StartProfiling(const Arguments& args) {
                                                     ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::StartProfiling(const int&)':
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: error: 'v8::HandleScope::HandleScope()' is protected
   V8_INLINE HandleScope() {}
             ^
../src/cpu_profiler.cc:58:21: error: within this context
         HandleScope scope;
                     ^
../src/cpu_profiler.cc:59:36: error: request for member 'Length' in 'args', which is of non-class type 'const int'
         Local<String> title = args.Length() > 0 ? args[0]->ToString() : String::New("");
                                    ^
../src/cpu_profiler.cc:59:57: error: invalid types 'const int[int]' for array subscript
         Local<String> title = args.Length() > 0 ? args[0]->ToString() : String::New("");
                                                         ^
../src/cpu_profiler.cc:59:73: error: 'New' is not a member of 'v8::String'
         Local<String> title = args.Length() > 0 ? args[0]->ToString() : String::New("");
                                                                         ^
../src/cpu_profiler.cc:60:46: error: cannot call member function 'void v8::CpuProfiler::StartProfiling(v8::Handle<v8::String>, bool)' without object
         v8::CpuProfiler::StartProfiling(title);
                                              ^
../src/cpu_profiler.cc:61:26: error: too few arguments to function 'v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)'
         return Undefined();
                          ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:323:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/cpu_profiler.cc: At global scope:
../src/cpu_profiler.cc:64:52: error: 'Arguments' does not name a type
     Handle<Value> CpuProfiler::StopProfiling(const Arguments& args) {
                                                    ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::StopProfiling(const int&)':
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: error: 'v8::HandleScope::HandleScope()' is protected
   V8_INLINE HandleScope() {}
             ^
../src/cpu_profiler.cc:65:21: error: within this context
         HandleScope scope;
                     ^
../src/cpu_profiler.cc:66:36: error: request for member 'Length' in 'args', which is of non-class type 'const int'
         Local<String> title = args.Length() > 0 ? args[0]->ToString() : String::New("");
                                    ^
../src/cpu_profiler.cc:66:57: error: invalid types 'const int[int]' for array subscript
         Local<String> title = args.Length() > 0 ? args[0]->ToString() : String::New("");
                                                         ^
../src/cpu_profiler.cc:66:73: error: 'New' is not a member of 'v8::String'
         Local<String> title = args.Length() > 0 ? args[0]->ToString() : String::New("");
                                                                         ^
../src/cpu_profiler.cc:67:73: error: cannot call member function 'v8::CpuProfile* v8::CpuProfiler::StopProfiling(v8::Handle<v8::String>)' without object
         const CpuProfile* profile = v8::CpuProfiler::StopProfiling(title);
                                                                         ^
../src/cpu_profiler.cc:68:22: error: 'class v8::HandleScope' has no member named 'Close'
         return scope.Close(Profile::New(profile));
                      ^
../src/cpu_profiler.cc: At global scope:
../src/cpu_profiler.cc:71:56: error: 'Arguments' does not name a type
     Handle<Value> CpuProfiler::DeleteAllProfiles(const Arguments& args) {
                                                        ^
../src/cpu_profiler.cc: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::DeleteAllProfiles(const int&)':
../src/cpu_profiler.cc:72:9: error: 'DeleteAllProfiles' is not a member of 'v8::CpuProfiler'
         v8::CpuProfiler::DeleteAllProfiles();
         ^
../src/cpu_profiler.cc:73:26: error: too few arguments to function 'v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)'
         return Undefined();
                          ^
In file included from /home/myguestuser/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../src/cpu_profiler.h:4,
                 from ../src/cpu_profiler.cc:1:
/home/myguestuser/.node-gyp/1.1.0/deps/v8/include/v8.h:323:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/cpu_profiler.cc: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::GetProfilesCount(const int&)':
../src/cpu_profiler.cc:31:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/cpu_profiler.cc: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::GetProfile(const int&)':
../src/cpu_profiler.cc:43:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/cpu_profiler.cc: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::FindProfile(const int&)':
../src/cpu_profiler.cc:55:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/cpu_profiler.cc: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::StartProfiling(const int&)':
../src/cpu_profiler.cc:62:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/cpu_profiler.cc: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::StopProfiling(const int&)':
../src/cpu_profiler.cc:69:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../src/cpu_profiler.cc: In static member function 'static v8::Handle<v8::Value> nodex::CpuProfiler::DeleteAllProfiles(const int&)':
../src/cpu_profiler.cc:74:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
profiler.target.mk:89: recipe for target 'Release/obj.target/profiler/src/cpu_profiler.o' failed
make: *** [Release/obj.target/profiler/src/cpu_profiler.o] Error 1
make: Leaving directory '/srv/node_modules/webkit-devtools-agent/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/node_modules/webkit-devtools-agent
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "webkit-devtools-agent"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! webkit-devtools-agent@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webkit-devtools-agent@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the webkit-devtools-agent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls webkit-devtools-agent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/npm-debug.log
myguestuser@91614db4b948:/srv$ 
```

**Comment by c4milo** [comment]
@ColCh yeah, sorry about that. I haven't started to migrate to IO.js just yet.

**Comment by thlorenz** [comment]
You should probably adapt to latest Nan like [we did for v8-profiler](https://github.com/node-inspector/v8-profiler/pull/71).

[this script](https://gist.github.com/thlorenz/7e9d8ad15566c99fd116) would help if you were using Nan currently, but maybe you can adapt it to help here as well.
